### PR TITLE
store and retrieve response status code

### PR DESCRIPTION
**Pull request by artursudnik**
Correction that stores and serves from cache http response status codes. This is important when for example part of application crashes after expensive computing and returns "500" to web browser. When responding with 200 status code and error message, response can be for example cached client side.

### CODE REVIEW

**Comment by rv-kip** [comment]
If this pull request is still desired, please fix the conflicts and we'll get it merged. Otherwise, please close.

**Comment by artursudnik** [comment]
fixed

**Comment by Spasfonx** [comment]
This PR will be merged some day ? I'm still facing this bug which return a `200` status code when a `500` is cached.

**Comment by artursudnik** [comment]
I wish it was.

**Comment by mattcasey** [comment]
Hi, the PR was merged but the latest version does not include it. Can we get a version bump?

**Pull request merged**
