### PR TITLE
Allow binary buffers

### PR DESCRIPTION
**Pull request by MDBox**
This will allow sending binary buffers by converting to a base64 string before storing to cache.  I added an option flag 'binary' to enable this feature.  
#51

``` javascript
router.get('/image/:guid', cache.route({binary: true}), function(req, res){
 ...
    res.status(200).send(new Buffer(body, 'binary'));
}
```

### CODE REVIEW

**Comment by co2-git** [comment]
+1

**Comment by rv-kip** [comment]
@MDBox, do you want to add a test for the binary flag? :)

**Comment by MDBox** [comment]
Sure, I can look at adding a test case.  Maybe this weekend.

**Comment by rv-kip** [comment]
Awesome. And add yourself to `contributors` in `package.json`.

**Comment by MDBox** [comment]
Test case added.

**Comment by rv-kip** [comment]
@MDBox thanks!

**Pull request merged**
