### PR TITLE
Add caching status codes

### PR DESCRIPTION
**Pull request by madelinecameron**
Somewhere along the line, this (https://github.com/rv-kip/express-redis-cache/commit/a24321bf13aa20d589052e5584745e3264dd819bb) seems to have gone missing. 

Here it is again. :)

### CODE REVIEW

**Comment by madelinecameron** [comment]
Oh. It seems it may have just not been merged in, just spotted another PR for this.

**Comment by mncrespi** [comment]
it works :+1:

**Comment by sebastianarena** [comment]
+1 to this problem, I just spent a couple of hours trying to figure out why a 500 error response from the server was showing sometimes as 200

**Comment by yuxinbo** [comment]
+1 to this problem, I just spent a couple of hours trying to figure out why a 404 error response from the server was showing sometimes as 200

**Comment by timtyrrell** [comment]
Same issue as above, super confused about getting 200's on bad requests, seems like a bad thing

**Comment by Loksly** [comment]
What about this? Seems to be a great problem the one that solves.

**Comment by kevinkuchar** [comment]
Any updates on this? Could really benefit from this being merged.

**Comment by madelinecameron** [comment]
Well, I think this has sat long enough. I'm cleaning up my repos (Happy New Years!) so I'm closing this.

**Pull request closed without merging**
