### PR TITLE
Fixes https://github.com/rv-kip/express-redis-cache/issues/59

### PR DESCRIPTION
**Pull request by ckeboss**
Fixes https://github.com/rv-kip/express-redis-cache/issues/59

### CODE REVIEW

**Comment by ckeboss** [comment]
Looks like the test's failed, I'll take a look later

**Comment by pswoodworth** [comment]
+1, this is particularly problematic right now as there's no way to conditionally not cache error statuses without this, as referenced in #64. thanks!

**Comment by ckeboss** [comment]
Anyone looking at this? @rv-kip

**Comment by rv-kip** [comment]
@ckeboss, Sorry. Been pretty busy.  Looks good. Could you add a test for a 0 value on `options.expire` to ensure it does the right thing?

**Comment by ckeboss** [comment]
@rv-kip I have added a test.

**Comment by ckeboss** [comment]
@rv-kip when will this get into a published version? Do you want to just publish a patch version or bundle other fixes/features before?

**Comment by rv-kip** [comment]
0.4.0 published.

**Pull request merged**
